services:
  clyvo-petcare-api:
    build: .
    image: clyvo-petcare-api:1.0
    container_name: clyvo-petcare-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://clyvo-h2-db:1521//opt/h2-data/clyvo-petcare-db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
    depends_on:
      - clyvo-h2-db
    restart: unless-stopped

  clyvo-h2-db:
    image: oscarfonts/h2:2.1.214
    container_name: clyvo-h2-db
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - clyvo_h2_data:/opt/h2-data
    restart: unless-stopped

volumes:
  clyvo_h2_data:
    name: clyvo_h2_data