-- ============================================================
-- SCRIPT DE BANCO DE DADOS - CLYVO PETCARE
-- PostgreSQL
-- ============================================================

-- Tabela principal de pets
CREATE TABLE TB_PET (
    ID_PET BIGINT GENERATED BY DEFAULT AS IDENTITY,
    NM_PET VARCHAR(100) NOT NULL,
    DS_ESPECIE VARCHAR(50) NOT NULL,
    DS_RACA VARCHAR(80),
    NR_PESO DOUBLE PRECISION,
    DT_NASCIMENTO DATE,
    NM_RESPONSAVEL VARCHAR(100) NOT NULL,
    DS_OBSERVACOES VARCHAR(255),

    CONSTRAINT PK_TB_PET PRIMARY KEY (ID_PET)
);

COMMENT ON TABLE TB_PET IS 'Cadastro dos animais atendidos pelo Clyvo PetCare';

COMMENT ON COLUMN TB_PET.ID_PET IS 'Identificador único do pet';
COMMENT ON COLUMN TB_PET.NM_PET IS 'Nome do pet';
COMMENT ON COLUMN TB_PET.DS_ESPECIE IS 'Espécie do pet';
COMMENT ON COLUMN TB_PET.DS_RACA IS 'Raça do pet';
COMMENT ON COLUMN TB_PET.NR_PESO IS 'Peso do pet em quilogramas';
COMMENT ON COLUMN TB_PET.DT_NASCIMENTO IS 'Data de nascimento do pet';
COMMENT ON COLUMN TB_PET.NM_RESPONSAVEL IS 'Nome do responsável pelo pet';
COMMENT ON COLUMN TB_PET.DS_OBSERVACOES IS 'Observações sobre o pet';


-- Tabela de alertas
CREATE TABLE TB_ALERTA (
    ID_ALERTA BIGINT GENERATED BY DEFAULT AS IDENTITY,
    TP_ALERTA VARCHAR(50) NOT NULL,
    DS_ALERTA VARCHAR(255) NOT NULL,
    DT_ALERTA DATE NOT NULL,
    ST_ALERTA VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
    ID_PET BIGINT NOT NULL,

    CONSTRAINT PK_TB_ALERTA PRIMARY KEY (ID_ALERTA),

    CONSTRAINT FK_ALERTA_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PET(ID_PET)
);

COMMENT ON TABLE TB_ALERTA IS 'Alertas e lembretes relacionados aos pets';

COMMENT ON COLUMN TB_ALERTA.ID_ALERTA IS 'Identificador único do alerta';
COMMENT ON COLUMN TB_ALERTA.TP_ALERTA IS 'Tipo do alerta';
COMMENT ON COLUMN TB_ALERTA.DS_ALERTA IS 'Descrição do alerta';
COMMENT ON COLUMN TB_ALERTA.DT_ALERTA IS 'Data programada para o alerta';
COMMENT ON COLUMN TB_ALERTA.ST_ALERTA IS 'Status do alerta';
COMMENT ON COLUMN TB_ALERTA.ID_PET IS 'Pet relacionado ao alerta';

-- ============================================================
-- DADOS INICIAIS PARA DEMONSTRAÇÃO
-- ============================================================

INSERT INTO TB_PET
(NM_PET, DS_ESPECIE, DS_RACA, NR_PESO, DT_NASCIMENTO, NM_RESPONSAVEL, DS_OBSERVACOES)
VALUES
('Nori', 'Réptil', 'Gecko-leopardo', 0.07, '2022-10-04', 'Matheus Almeida', 'Acompanhamento preventivo de temperatura, umidade e rotina alimentar'),
('Mel', 'Cachorro', 'Golden Retriever', 28.5, '2020-06-15', 'Ana Souza', 'Acompanhamento de vacinação e consultas preventivas');

INSERT INTO TB_ALERTA
(TP_ALERTA, DS_ALERTA, DT_ALERTA, ST_ALERTA, ID_PET)
VALUES
('DERMATOLOGICO', 'Acompanhamento de ferida na pele', '2026-09-18', 'PENDENTE', 1),
('VACINACAO', 'Verificar necessidade de reforço vacinal', '2026-10-05', 'PENDENTE', 2);
